---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deprecate Application

on:
  workflow_dispatch:
    inputs:
      app:
        type: string
        description: Application Name
        required: true
      reason:
        type: string
        description: Deprecation Reason
        required: true
      release:
        type: boolean
        description: Create Release
        default: true

permissions:
  contents: read

jobs:
  plan:
    name: Plan (${{ inputs.app }})
    runs-on: ubuntu-latest
    outputs:
      pull-number: ${{ steps.pr.outputs.pull-request-number }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Generate Token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Delete App Directory
        run: |
          rm -rf ./apps/${{ inputs.app }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        id: pr
        with:
          body: |
            **Reason**: ${{ inputs.reason }}
          branch: deprecate/${{ inputs.app }}
          commit-message: "release(${{ inputs.app }})!: deprecate container image"
          sign-commits: true
          signoff: true
          title: "release(${{ inputs.app }})!: deprecate container image"
          token: ${{ steps.app-token.outputs.token }}

  merge:
    if: ${{ inputs.release }}
    name: Merge (${{ inputs.app }})
    needs: ["plan"]
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Merge Pull Request
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ needs.plan.outputs.pull-number }},
              merge_method: 'squash',
            });

  announce:
    if: ${{ inputs.release }}
    name: Announce (${{ inputs.app }})
    needs: ["merge"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Generate Token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Get Release Tag
        uses: ./.github/actions/release-tag
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Create Release
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1.18.0
        with:
          body: |
            > [!WARNING]
            > An application has been deprecated and will no longer receive updates.
            > After **6 months** from now, its image will be **removed** from our container registry.

            ## ðŸ“¦ Application

            **Name**: ${{ inputs.app }}
            **Reason**: ${{ inputs.reason }}
          tag: ${{ steps.release.outputs.tag }}
          token: ${{ steps.app-token.outputs.token }}
